### PR TITLE
Fix route viewer crash

### PR DESCRIPTION
**Pull request by amy-corson-ibigroup**
**Description:**

Fixes a regression that was causing a crash when trying to use the route viewer! 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
We should probably put a better check here but for now this is ok. @daniel-heppner-ibigroup this is the solution to the crash I was talking about

**Review by daniel-heppner-ibigroup — APPROVED** [review]
Looks fine, we use this approach elsewhere in this file so I think it's ok. But why are the a11y tests failing?

**Comment by daniel-heppner-ibigroup** [comment]
I was able to fix the a11y tests. It looks like this change uncovered another fix I should have made in a recent PR. Thanks for that!

**Comment by daniel-heppner-ibigroup** [comment]
I was able to fix the a11y tests. It looks like this change uncovered another fix I should have made in a recent PR. Thanks for that!

**Pull request merged**
