### PR TITLE
feat(ItineraryBody): Add fare info in each transit leg body (new config)

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
This PR add support for displaying fare information introduced by https://github.com/opentripplanner/otp-ui/pull/209.

### New configuration variable

Insert a new configuration variable in `config.yml`:

```yml
# New: itinerary options
itinerary:
  # Show fares for each transit leg (false if omitted).
  # (Requires using LineItinerary.)
  showRouteFares: true
```

### To test
In `tabbed-itineraries`, insert
```js
import LineItinerary from './line-itin/line-itinerary'
```
and change these defaults:
```js
  static defaultProps = {
    itineraryClass: LineItinerary
  }
```

Then `yarn start` and open the URL below, expand the `Ride x mins/n stops` button, and see the fare displayed below the stops list: 
http://localhost:9966/#/?ui_activeSearch=9jwmo0s95&ui_activeItinerary=0&fromPlace=1801%20Atlanta%20Ave%2C%20Orlando%2C%20FL%2C%20USA%3A%3A28.52255017622969%2C-81.38225555419923&toPlace=2506%20N%20Orange%20Ave%2C%20Orlando%2C%20FL%2C%20USA%3A%3A28.57412028580987%2C-81.37281417846681&date=2020-09-08&time=10%3A30&arriveBy=false&mode=WALK%2CBUS%2CRAIL&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=false&companies=&bannedRoutes=&numItineraries=3&otherThanPreferredRoutesPenalty=900&preferredRoutes=

### CODE REVIEW

**Review by landonreed — CHANGES_REQUESTED** [review]
Looks really good. We should also update the default config though.

**Comment by binh-dam-ibigroup** [comment]
> Looks really good. We should also update the default config though.

Yep. Totally forgot about that one.

**Review by landonreed — APPROVED** [review]

**Pull request merged**
