### PR TITLE
Break import cycles

### LINKED ISSUE #740: Some actions are not properly initialized
With local storage persistence enabled:
```yaml
persistence:
  enabled: true
  strategy: localStorage
```

clicking on `yes` to the question `Remember recent searches/places?` generates the following error:

error-enable-tracking

This is due to import cycles in the code. One example of these is `components/form/user-settings.js -> actions/api.js -> util/state.js -> components/form/user-settings.js`.
After breaking some of these cycles, the code works again as expected.

I created a test branch (https://github.com/otrichet/otp-react-redux/commits/import-cyles) to
- add a plugin that detects these cycles at build time (commit https://github.com/otrichet/otp-react-redux/commit/adcd23a6c7f0ac0e7f786a6c15153032d2b253a6)
- break some of these cycles to confirm it solves this issue (commits https://github.com/otrichet/otp-react-redux/commit/2f97dcec22e14d841404cc9fe16b6567207826bd and https://github.com/otrichet/otp-react-redux/commit/8fe2d4d0e3e6250ff28e6f07ee763d1800840377)

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
Close #740 by removing import cycles. Thank you for @otrichet for finding this fix and writing most of the commits. This PR makes these changes compatible with #739. 

~This PR is therefore blocked by #739~

Changes are mostly around:
- Moving mobile screen ids around,
- Moving actions between `map`, `form`, and `user`.
- Moving code around user settings when using local storage.

### CODE REVIEW

**Comment by binh-dam-ibigroup** [comment]
FYI @miles-grant-ibigroup there are now merge conflicts

**Comment by miles-grant-ibigroup** [comment]
I propose blocking this again until all the accessibility stuff is merged. Things are only going to get worse and it's looking like re-creating this PR from scratch might be the best option...

**Comment by binh-dam-ibigroup** [comment]
@miles-grant-ibigroup I resolved a few dependency cycles, but I am not sure whether we want/need to deal with all of them in the PR, was that your impression?

**Comment by miles-grant-ibigroup** [comment]
Wow this is lots of work thanks very much for doing all this! Agreed this PR should be about adding the check, removing the rest can be technical debt. Some of them will also go away once we remove otp1 support.

**Comment by miles-grant-ibigroup** [comment]
I would approve this PR but since I "opened" it I cannot

**Review by binh-dam-ibigroup — APPROVED** [review]
Approving since @miles-grant-ibigroup started this and I took over and he approved.

**Review by amy-corson-ibigroup — APPROVED** [review]
Couldn't spot any issues! Thanks so much to all three of you for the work!

**Pull request merged**
