### PR TITLE
fix(responsive-webapp): prevent error in safari positioning

### PR DESCRIPTION
**Pull request by amy-corson-ibigroup**
**Description:**
Fix bug where current location was returning an error on mobile safari browsers. NOTE that this reverts https://github.com/opentripplanner/otp-react-redux/pull/697. I tested for the bug outlined in that PR, and could not reproduce any issues. Could be related to a webkit update? 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Review by binh-dam-ibigroup — APPROVED** [review]
Gonna pass this. Just a note that I am not able to get the map centering to my current position on Safari for Mac, either on this branch or on the dev branch.

**Review by josh-willis-arcadis — APPROVED** [review]
LGTM!

**Comment by amy-corson-ibigroup** [comment]
> I am not able to get the map centering to my current position on Safari for Mac

This was technically a different issue, but thanks for catching it!! The `GeolocateControl` was returning a timeout error. I fixed this by adding `enableHighAccuracy` based on this: https://stackoverflow.com/questions/46689339/ionic-2-geolocation-timeout-error 

The map current position button seems to be working for me now on all browsers. Added to this PR since it seems similar enough but let me know if you notice issues or want to see this split into a different PR @binh-dam-ibigroup @josh-willis-arcadis

**Comment by amy-corson-ibigroup** [comment]
> The `GeolocateControl` was returning a timeout error. I fixed this by adding `enableHighAccuracy`

I nixed this because it wasn't behaving consistently! Opening a new PR to address this issue

**Pull request merged**
