### PR TITLE
Fix notifications prefs

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
This PR fixes a regression that makes garbled text show for trip notifications thresholds.

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
Fixes the issue thanks for catching!

**Comment by miles-grant-ibigroup** [comment]
As for the failing Percy tests, those are fixed by https://github.com/opentripplanner/otp-react-redux/pull/796. That PR should block this

**Comment by demory** [comment]
I am testing this now -- the issue with the garbled dropdowns appears fixed, but I am also consistently seeing an issue where it does not let you select any days to follow the saved trip:

image

@binh-dam-ibigroup / @miles-grant-ibigroup are you able to reproduce? Not sure if this is an unrelated issue or not.

I am running with the current `sound-transit-qa` config, master branch. I have tried merging the latest otp-rr `dev` into this branch (same thing before and after). I have tried wiping node_modules.

**Comment by miles-grant-ibigroup** [comment]
@demory does switching to dev fix this for you? To my knowledge this is a long-standing otp-middleware bug

**Review by demory — APPROVED** [review]

**Comment by binh-dam-ibigroup** [comment]
> @demory does switching to dev fix this for you? To my knowledge this is a long-standing otp-middleware bug

Looks like this was "fixed" with the latest middleware deployment?

**Pull request merged**
