### PR TITLE
refactor: avoid un-needed time chop-off

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
**Description:**

Itinerary body was sometimes breaking time text when it shouldn't be. This PR resolves this. Will leave PR open for now to collect other styling regressions.

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Comment by binh-dam-ibigroup** [comment]
Just came across this one. Could setting the time-column component to have `min-width: 60px` and remove `width: 60px` do the trick regardless of the width of the containers?

**Comment by miles-grant-ibigroup** [comment]
Possibly! I know there are a lot of nesting styles going on here and then quite a bit of a11y changes happened as well so I'll have to spend some proper time with it to double check that doesn't introduce any regressions

**Comment by AdrianaCeric** [comment]
I found that removing the width also did the trick. I think this is a lazy hack, but I've yet to find something else. Will look into it more, but let me know if you have any comments/suggestions!

**Review by binh-dam-ibigroup — APPROVED** [review]

**Comment by miles-grant-ibigroup** [comment]
Removing styles is always a good thing!

**Pull request closed without merging**
