### PR TITLE
Add `sortOrder` to route requests

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
**Description:**
Adds sort order to route requests. Enables the existing route sort order sorter.

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Review by daniel-heppner-ibigroup — APPROVED** [review]
Cool thanks for the addition

**Comment by nukeador** [comment]
Not sure if it's because this change merged into dev, but route list is currently broken in my local setup

```
The development server has disconnected.
Refresh the page if necessary. webpackHotDevClient.js:76:13
[HMR] Waiting for update signal from WDS... log.js:24
unreachable code after return statement bundle.js:705:3
Config value 'homeTimezone' not configured for this webapp!

      This value is recommended in order to properly display stop times for
      users that are not in the timezone that the transit system is in. The
      detected user timezone of 'Europe/Madrid' will be used. Hopefully
      that is the right one... create-otp-reducer.js:89
No reducer provided for key "callTaker" index.js:1
No localization messages found for es in @opentripplanner/building-blocks i18n.js:101
No localization messages found for es in @opentripplanner/core-utils i18n.js:101
No localization messages found for es in @opentripplanner/geocoder i18n.js:101
No localization messages found for es in @opentripplanner/humanize-distance i18n.js:101
No localization messages found for es in @opentripplanner/icons i18n.js:101
No localization messages found for es in @opentripplanner/location-icon i18n.js:101
No localization messages found for es in @opentripplanner/otp2-tile-overlay i18n.js:101
No localization messages found for es in @opentripplanner/park-and-ride-overlay i18n.js:101
No localization messages found for es in @opentripplanner/route-viewer-overlay i18n.js:101
No localization messages found for es in @opentripplanner/stop-viewer-overlay i18n.js:101
No localization messages found for es in @opentripplanner/stops-overlay i18n.js:101
No localization messages found for es in @opentripplanner/transitive-overlay i18n.js:101
No localization messages found for es in @opentripplanner/trip-viewer-overlay i18n.js:101
No localization messages found for es in @opentripplanner/vehicle-rental-overlay i18n.js:101
 action UPDATE_LOCALE @ 20:00:16.399 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "UPDATE_LOCALE", payload: {…} }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
 action @@router/LOCATION_CHANGE @ 20:00:16.407 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "@@router/LOCATION_CHANGE", payload: {…} }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
Warning: React does not recognize the `toParams` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `toparams` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by Connect(Component))
    in Connect(Component) (created by ViewSwitcher)
    in div (created by ViewSwitcher)
    in ViewSwitcher (created by DesktopNav)
    in div (created by NavbarHeader)
    in NavbarHeader (created by DesktopNav)
    in div (created by Grid)
    in Grid (created by Navbar)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by DesktopNav)
    in header (created by DesktopNav)
    in DesktopNav (created by Connect(DesktopNav))
    in Connect(DesktopNav) (created by ResponsiveWebapp)
    in div (created by ResponsiveWebapp)
    in ResponsiveWebapp (created by Connect(ResponsiveWebapp))
    in Connect(ResponsiveWebapp) (created by Context.Consumer)
    in injectIntl(Connect(ResponsiveWebapp)) (created by WrappedComponent)
    in WrappedComponent (created by UserLoaderScreen)
    in UserLoaderScreen (created by Context.Consumer)
    in injectIntl(UserLoaderScreen) (created by Connect(injectIntl(UserLoaderScreen)))
    in Connect(injectIntl(UserLoaderScreen)) (created by Context.Consumer)
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter() (created by Context.Consumer)
    in Route (created by RouterWrapperWithAuth0)
    in Switch (created by RouterWrapperWithAuth0)
    in QueryParamProviderInner (created by ReactRouter5Adapter)
    in ReactRouter5Adapter (created by QueryParamProvider)
    in QueryParamProvider (created by RouterWrapperWithAuth0)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Connect(ConnectedRouterWithContext))
    in Connect(ConnectedRouterWithContext) (created by RouterWrapperWithAuth0)
    in IntlProvider (created by RouterWrapperWithAuth0)
    in MapProvider (created by RouterWrapperWithAuth0)
    in RouterWrapperWithAuth0 (created by Connect(RouterWrapperWithAuth0))
    in Connect(RouterWrapperWithAuth0) (created by Webapp)
    in Webapp
    in Provider index.js:1
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ModeSelector`. See https://fb.me/react-warning-keys for more information.
    in ModeButton (created by ModeSelector)
    in ModeSelector (created by BatchSettings)
    in div (created by styled.div)
    in styled.div (created by BatchSettings)
    in div (created by styled.div)
    in styled.div (created by BatchSettings)
    in BatchSettings (created by Connect(BatchSettings))
    in Connect(BatchSettings) (created by BatchRoutingPanel)
    in form (created by BatchRoutingPanel)
    in div (created by ViewerContainer)
    in ViewerContainer (created by Connect(ViewerContainer))
    in Connect(ViewerContainer) (created by BatchRoutingPanel)
    in BatchRoutingPanel (created by Context.Consumer)
    in injectIntl(BatchRoutingPanel) (created by Connect(injectIntl(BatchRoutingPanel)))
    in Connect(injectIntl(BatchRoutingPanel)) (created by ResponsiveWebapp)
    in main (created by ResponsiveWebapp)
    in div (created by Col)
    in Col (created by ResponsiveWebapp)
    in div (created by Row)
    in Row (created by ResponsiveWebapp)
    in div (created by Grid)
    in Grid (created by ResponsiveWebapp)
    in div (created by ResponsiveWebapp)
    in ResponsiveWebapp (created by Connect(ResponsiveWebapp))
    in Connect(ResponsiveWebapp) (created by Context.Consumer)
    in injectIntl(Connect(ResponsiveWebapp)) (created by WrappedComponent)
    in WrappedComponent (created by UserLoaderScreen)
    in UserLoaderScreen (created by Context.Consumer)
    in injectIntl(UserLoaderScreen) (created by Connect(injectIntl(UserLoaderScreen)))
    in Connect(injectIntl(UserLoaderScreen)) (created by Context.Consumer)
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter() (created by Context.Consumer)
    in Route (created by RouterWrapperWithAuth0)
    in Switch (created by RouterWrapperWithAuth0)
    in QueryParamProviderInner (created by ReactRouter5Adapter)
    in ReactRouter5Adapter (created by QueryParamProvider)
    in QueryParamProvider (created by RouterWrapperWithAuth0)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Connect(ConnectedRouterWithContext))
    in Connect(ConnectedRouterWithContext) (created by RouterWrapperWithAuth0)
    in IntlProvider (created by RouterWrapperWithAuth0)
    in MapProvider (created by RouterWrapperWithAuth0)
    in RouterWrapperWithAuth0 (created by Connect(RouterWrapperWithAuth0))
    in Connect(RouterWrapperWithAuth0) (created by Webapp)
    in Webapp
    in Provider index.js:1
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Navbar) react-dom.development.js:88
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Navbar) react-dom.development.js:88
 action SET_VIEWED_ROUTE @ 20:00:16.488 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "SET_VIEWED_ROUTE", payload: null }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack tiny-warning.esm.js:11
 action SET_MAIN_PANEL_CONTENT @ 20:00:16.490 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "SET_MAIN_PANEL_CONTENT", payload: 1 }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack tiny-warning.esm.js:11
 action FINDING_ROUTES @ 20:00:16.512 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "FINDING_ROUTES" }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
 action FIND_ROUTES_ERROR @ 20:00:16.651 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "FIND_ROUTES_ERROR", payload: (1) […] }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
no mode/route type found for route FIND_ROUTES_ERROR route.js:217
no mode/route type found for route 
Array [ {…} ]
route.js:217
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RouteViewer`. See https://fb.me/react-warning-keys for more information.
    in RouteRow (created by RouteViewer)
    in RouteViewer (created by Context.Consumer)
    in injectIntl(RouteViewer) (created by Connect(injectIntl(RouteViewer)))
    in Connect(injectIntl(RouteViewer)) (created by ViewerContainer)
    in ViewerContainer (created by Connect(ViewerContainer))
    in Connect(ViewerContainer) (created by BatchRoutingPanel)
    in BatchRoutingPanel (created by Context.Consumer)
    in injectIntl(BatchRoutingPanel) (created by Connect(injectIntl(BatchRoutingPanel)))
    in Connect(injectIntl(BatchRoutingPanel)) (created by ResponsiveWebapp)
    in main (created by ResponsiveWebapp)
    in div (created by Col)
    in Col (created by ResponsiveWebapp)
    in div (created by Row)
    in Row (created by ResponsiveWebapp)
    in div (created by Grid)
    in Grid (created by ResponsiveWebapp)
    in div (created by ResponsiveWebapp)
    in ResponsiveWebapp (created by Connect(ResponsiveWebapp))
    in Connect(ResponsiveWebapp) (created by Context.Consumer)
    in injectIntl(Connect(ResponsiveWebapp)) (created by WrappedComponent)
    in WrappedComponent (created by UserLoaderScreen)
    in UserLoaderScreen (created by Context.Consumer)
    in injectIntl(UserLoaderScreen) (created by Connect(injectIntl(UserLoaderScreen)))
    in Connect(injectIntl(UserLoaderScreen)) (created by Context.Consumer)
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter() (created by Context.Consumer)
    in Route (created by RouterWrapperWithAuth0)
    in Switch (created by RouterWrapperWithAuth0)
    in QueryParamProviderInner (created by ReactRouter5Adapter)
    in ReactRouter5Adapter (created by QueryParamProvider)
    in QueryParamProvider (created by RouterWrapperWithAuth0)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Connect(ConnectedRouterWithContext))
    in Connect(ConnectedRouterWithContext) (created by RouterWrapperWithAuth0)
    in IntlProvider (created by RouterWrapperWithAuth0)
    in MapProvider (created by RouterWrapperWithAuth0)
    in RouterWrapperWithAuth0 (created by Connect(RouterWrapperWithAuth0))
    in Connect(RouterWrapperWithAuth0) (created by Webapp)
    in Webapp
    in Provider index.js:1
Warning: React does not recognize the `patternActive` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `patternactive` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by Button)
    in Button (created by Styled(Button))
    in Styled(Button) (created by RouteRow)
    in li (created by styled.li)
    in styled.li (created by RouteRow)
    in RouteRow (created by RouteViewer)
    in ul (created by RouteViewer)
    in div (created by RouteViewer)
    in RouteViewer (created by Context.Consumer)
    in injectIntl(RouteViewer) (created by Connect(injectIntl(RouteViewer)))
    in Connect(injectIntl(RouteViewer)) (created by ViewerContainer)
    in ViewerContainer (created by Connect(ViewerContainer))
    in Connect(ViewerContainer) (created by BatchRoutingPanel)
    in BatchRoutingPanel (created by Context.Consumer)
    in injectIntl(BatchRoutingPanel) (created by Connect(injectIntl(BatchRoutingPanel)))
    in Connect(injectIntl(BatchRoutingPanel)) (created by ResponsiveWebapp)
    in main (created by ResponsiveWebapp)
    in div (created by Col)
    in Col (created by ResponsiveWebapp)
    in div (created by Row)
    in Row (created by ResponsiveWebapp)
    in div (created by Grid)
    in Grid (created by ResponsiveWebapp)
    in div (created by ResponsiveWebapp)
    in ResponsiveWebapp (created by Connect(ResponsiveWebapp))
    in Connect(ResponsiveWebapp) (created by Context.Consumer)
    in injectIntl(Connect(ResponsiveWebapp)) (created by WrappedComponent)
    in WrappedComponent (created by UserLoaderScreen)
    in UserLoaderScreen (created by Context.Consumer)
    in injectIntl(UserLoaderScreen) (created by Connect(injectIntl(UserLoaderScreen)))
    in Connect(injectIntl(UserLoaderScreen)) (created by Context.Consumer)
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter() (created by Context.Consumer)
    in Route (created by RouterWrapperWithAuth0)
    in Switch (created by RouterWrapperWithAuth0)
    in QueryParamProviderInner (created by ReactRouter5Adapter)
    in ReactRouter5Adapter (created by QueryParamProvider)
    in QueryParamProvider (created by RouterWrapperWithAuth0)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Connect(ConnectedRouterWithContext))
    in Connect(ConnectedRouterWithContext) (created by RouterWrapperWithAuth0)
    in IntlProvider (created by RouterWrapperWithAuth0)
    in MapProvider (created by RouterWrapperWithAuth0)
    in RouterWrapperWithAuth0 (created by Connect(RouterWrapperWithAuth0))
    in Connect(RouterWrapperWithAuth0) (created by Webapp)
    in Webapp
    in Provider index.js:1
 action FIND_ROUTES_RESPONSE @ 20:00:16.657 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "FIND_ROUTES_RESPONSE", payload: {…} }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
HTTPS-Only Mode: Upgrading insecure request “http://basemaps.cartocdn.com/gl/positron-gl-style/style.json” to use “https”. style.json
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 6
```

```
The development server has disconnected.
Refresh the page if necessary. webpackHotDevClient.js:76:13
[HMR] Waiting for update signal from WDS... log.js:24
unreachable code after return statement bundle.js:705:3
Config value 'homeTimezone' not configured for this webapp!

      This value is recommended in order to properly display stop times for
      users that are not in the timezone that the transit system is in. The
      detected user timezone of 'Europe/Madrid' will be used. Hopefully
      that is the right one... create-otp-reducer.js:89
No reducer provided for key "callTaker" index.js:1
No localization messages found for es in @opentripplanner/building-blocks i18n.js:101
No localization messages found for es in @opentripplanner/core-utils i18n.js:101
No localization messages found for es in @opentripplanner/geocoder i18n.js:101
No localization messages found for es in @opentripplanner/humanize-distance i18n.js:101
No localization messages found for es in @opentripplanner/icons i18n.js:101
No localization messages found for es in @opentripplanner/location-icon i18n.js:101
No localization messages found for es in @opentripplanner/otp2-tile-overlay i18n.js:101
No localization messages found for es in @opentripplanner/park-and-ride-overlay i18n.js:101
No localization messages found for es in @opentripplanner/route-viewer-overlay i18n.js:101
No localization messages found for es in @opentripplanner/stop-viewer-overlay i18n.js:101
No localization messages found for es in @opentripplanner/stops-overlay i18n.js:101
No localization messages found for es in @opentripplanner/transitive-overlay i18n.js:101
No localization messages found for es in @opentripplanner/trip-viewer-overlay i18n.js:101
No localization messages found for es in @opentripplanner/vehicle-rental-overlay i18n.js:101
 action UPDATE_LOCALE @ 20:00:16.399 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "UPDATE_LOCALE", payload: {…} }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
 action @@router/LOCATION_CHANGE @ 20:00:16.407 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "@@router/LOCATION_CHANGE", payload: {…} }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
Warning: React does not recognize the `toParams` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `toparams` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by Connect(Component))
    in Connect(Component) (created by ViewSwitcher)
    in div (created by ViewSwitcher)
    in ViewSwitcher (created by DesktopNav)
    in div (created by NavbarHeader)
    in NavbarHeader (created by DesktopNav)
    in div (created by Grid)
    in Grid (created by Navbar)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by DesktopNav)
    in header (created by DesktopNav)
    in DesktopNav (created by Connect(DesktopNav))
    in Connect(DesktopNav) (created by ResponsiveWebapp)
    in div (created by ResponsiveWebapp)
    in ResponsiveWebapp (created by Connect(ResponsiveWebapp))
    in Connect(ResponsiveWebapp) (created by Context.Consumer)
    in injectIntl(Connect(ResponsiveWebapp)) (created by WrappedComponent)
    in WrappedComponent (created by UserLoaderScreen)
    in UserLoaderScreen (created by Context.Consumer)
    in injectIntl(UserLoaderScreen) (created by Connect(injectIntl(UserLoaderScreen)))
    in Connect(injectIntl(UserLoaderScreen)) (created by Context.Consumer)
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter() (created by Context.Consumer)
    in Route (created by RouterWrapperWithAuth0)
    in Switch (created by RouterWrapperWithAuth0)
    in QueryParamProviderInner (created by ReactRouter5Adapter)
    in ReactRouter5Adapter (created by QueryParamProvider)
    in QueryParamProvider (created by RouterWrapperWithAuth0)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Connect(ConnectedRouterWithContext))
    in Connect(ConnectedRouterWithContext) (created by RouterWrapperWithAuth0)
    in IntlProvider (created by RouterWrapperWithAuth0)
    in MapProvider (created by RouterWrapperWithAuth0)
    in RouterWrapperWithAuth0 (created by Connect(RouterWrapperWithAuth0))
    in Connect(RouterWrapperWithAuth0) (created by Webapp)
    in Webapp
    in Provider index.js:1
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ModeSelector`. See https://fb.me/react-warning-keys for more information.
    in ModeButton (created by ModeSelector)
    in ModeSelector (created by BatchSettings)
    in div (created by styled.div)
    in styled.div (created by BatchSettings)
    in div (created by styled.div)
    in styled.div (created by BatchSettings)
    in BatchSettings (created by Connect(BatchSettings))
    in Connect(BatchSettings) (created by BatchRoutingPanel)
    in form (created by BatchRoutingPanel)
    in div (created by ViewerContainer)
    in ViewerContainer (created by Connect(ViewerContainer))
    in Connect(ViewerContainer) (created by BatchRoutingPanel)
    in BatchRoutingPanel (created by Context.Consumer)
    in injectIntl(BatchRoutingPanel) (created by Connect(injectIntl(BatchRoutingPanel)))
    in Connect(injectIntl(BatchRoutingPanel)) (created by ResponsiveWebapp)
    in main (created by ResponsiveWebapp)
    in div (created by Col)
    in Col (created by ResponsiveWebapp)
    in div (created by Row)
    in Row (created by ResponsiveWebapp)
    in div (created by Grid)
    in Grid (created by ResponsiveWebapp)
    in div (created by ResponsiveWebapp)
    in ResponsiveWebapp (created by Connect(ResponsiveWebapp))
    in Connect(ResponsiveWebapp) (created by Context.Consumer)
    in injectIntl(Connect(ResponsiveWebapp)) (created by WrappedComponent)
    in WrappedComponent (created by UserLoaderScreen)
    in UserLoaderScreen (created by Context.Consumer)
    in injectIntl(UserLoaderScreen) (created by Connect(injectIntl(UserLoaderScreen)))
    in Connect(injectIntl(UserLoaderScreen)) (created by Context.Consumer)
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter() (created by Context.Consumer)
    in Route (created by RouterWrapperWithAuth0)
    in Switch (created by RouterWrapperWithAuth0)
    in QueryParamProviderInner (created by ReactRouter5Adapter)
    in ReactRouter5Adapter (created by QueryParamProvider)
    in QueryParamProvider (created by RouterWrapperWithAuth0)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Connect(ConnectedRouterWithContext))
    in Connect(ConnectedRouterWithContext) (created by RouterWrapperWithAuth0)
    in IntlProvider (created by RouterWrapperWithAuth0)
    in MapProvider (created by RouterWrapperWithAuth0)
    in RouterWrapperWithAuth0 (created by Connect(RouterWrapperWithAuth0))
    in Connect(RouterWrapperWithAuth0) (created by Webapp)
    in Webapp
    in Provider index.js:1
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Navbar) react-dom.development.js:88
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Navbar) react-dom.development.js:88
 action SET_VIEWED_ROUTE @ 20:00:16.488 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "SET_VIEWED_ROUTE", payload: null }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack tiny-warning.esm.js:11
 action SET_MAIN_PANEL_CONTENT @ 20:00:16.490 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "SET_MAIN_PANEL_CONTENT", payload: 1 }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack tiny-warning.esm.js:11
 action FINDING_ROUTES @ 20:00:16.512 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "FINDING_ROUTES" }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
 action FIND_ROUTES_ERROR @ 20:00:16.651 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "FIND_ROUTES_ERROR", payload: (1) […] }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
no mode/route type found for route FIND_ROUTES_ERROR route.js:217
no mode/route type found for route 
Array [ {…} ]
route.js:217
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RouteViewer`. See https://fb.me/react-warning-keys for more information.
    in RouteRow (created by RouteViewer)
    in RouteViewer (created by Context.Consumer)
    in injectIntl(RouteViewer) (created by Connect(injectIntl(RouteViewer)))
    in Connect(injectIntl(RouteViewer)) (created by ViewerContainer)
    in ViewerContainer (created by Connect(ViewerContainer))
    in Connect(ViewerContainer) (created by BatchRoutingPanel)
    in BatchRoutingPanel (created by Context.Consumer)
    in injectIntl(BatchRoutingPanel) (created by Connect(injectIntl(BatchRoutingPanel)))
    in Connect(injectIntl(BatchRoutingPanel)) (created by ResponsiveWebapp)
    in main (created by ResponsiveWebapp)
    in div (created by Col)
    in Col (created by ResponsiveWebapp)
    in div (created by Row)
    in Row (created by ResponsiveWebapp)
    in div (created by Grid)
    in Grid (created by ResponsiveWebapp)
    in div (created by ResponsiveWebapp)
    in ResponsiveWebapp (created by Connect(ResponsiveWebapp))
    in Connect(ResponsiveWebapp) (created by Context.Consumer)
    in injectIntl(Connect(ResponsiveWebapp)) (created by WrappedComponent)
    in WrappedComponent (created by UserLoaderScreen)
    in UserLoaderScreen (created by Context.Consumer)
    in injectIntl(UserLoaderScreen) (created by Connect(injectIntl(UserLoaderScreen)))
    in Connect(injectIntl(UserLoaderScreen)) (created by Context.Consumer)
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter() (created by Context.Consumer)
    in Route (created by RouterWrapperWithAuth0)
    in Switch (created by RouterWrapperWithAuth0)
    in QueryParamProviderInner (created by ReactRouter5Adapter)
    in ReactRouter5Adapter (created by QueryParamProvider)
    in QueryParamProvider (created by RouterWrapperWithAuth0)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Connect(ConnectedRouterWithContext))
    in Connect(ConnectedRouterWithContext) (created by RouterWrapperWithAuth0)
    in IntlProvider (created by RouterWrapperWithAuth0)
    in MapProvider (created by RouterWrapperWithAuth0)
    in RouterWrapperWithAuth0 (created by Connect(RouterWrapperWithAuth0))
    in Connect(RouterWrapperWithAuth0) (created by Webapp)
    in Webapp
    in Provider index.js:1
Warning: React does not recognize the `patternActive` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `patternactive` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by Button)
    in Button (created by Styled(Button))
    in Styled(Button) (created by RouteRow)
    in li (created by styled.li)
    in styled.li (created by RouteRow)
    in RouteRow (created by RouteViewer)
    in ul (created by RouteViewer)
    in div (created by RouteViewer)
    in RouteViewer (created by Context.Consumer)
    in injectIntl(RouteViewer) (created by Connect(injectIntl(RouteViewer)))
    in Connect(injectIntl(RouteViewer)) (created by ViewerContainer)
    in ViewerContainer (created by Connect(ViewerContainer))
    in Connect(ViewerContainer) (created by BatchRoutingPanel)
    in BatchRoutingPanel (created by Context.Consumer)
    in injectIntl(BatchRoutingPanel) (created by Connect(injectIntl(BatchRoutingPanel)))
    in Connect(injectIntl(BatchRoutingPanel)) (created by ResponsiveWebapp)
    in main (created by ResponsiveWebapp)
    in div (created by Col)
    in Col (created by ResponsiveWebapp)
    in div (created by Row)
    in Row (created by ResponsiveWebapp)
    in div (created by Grid)
    in Grid (created by ResponsiveWebapp)
    in div (created by ResponsiveWebapp)
    in ResponsiveWebapp (created by Connect(ResponsiveWebapp))
    in Connect(ResponsiveWebapp) (created by Context.Consumer)
    in injectIntl(Connect(ResponsiveWebapp)) (created by WrappedComponent)
    in WrappedComponent (created by UserLoaderScreen)
    in UserLoaderScreen (created by Context.Consumer)
    in injectIntl(UserLoaderScreen) (created by Connect(injectIntl(UserLoaderScreen)))
    in Connect(injectIntl(UserLoaderScreen)) (created by Context.Consumer)
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter() (created by Context.Consumer)
    in Route (created by RouterWrapperWithAuth0)
    in Switch (created by RouterWrapperWithAuth0)
    in QueryParamProviderInner (created by ReactRouter5Adapter)
    in ReactRouter5Adapter (created by QueryParamProvider)
    in QueryParamProvider (created by RouterWrapperWithAuth0)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Connect(ConnectedRouterWithContext))
    in Connect(ConnectedRouterWithContext) (created by RouterWrapperWithAuth0)
    in IntlProvider (created by RouterWrapperWithAuth0)
    in MapProvider (created by RouterWrapperWithAuth0)
    in RouterWrapperWithAuth0 (created by Connect(RouterWrapperWithAuth0))
    in Connect(RouterWrapperWithAuth0) (created by Webapp)
    in Webapp
    in Provider index.js:1
 action FIND_ROUTES_RESPONSE @ 20:00:16.657 core.js:104
 prev state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:116
 action     
Object { type: "FIND_ROUTES_RESPONSE", payload: {…} }
core.js:120
 next state 
Object { otp: {…}, router: {…}, user: {…} }
core.js:128
HTTPS-Only Mode: Upgrading insecure request “http://basemaps.cartocdn.com/gl/positron-gl-style/style.json” to use “https”. style.json
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 6
```

**Comment by miles-grant-ibigroup** [comment]
Make sure you are using the latest version of OTP! @nukeador

**Comment by nukeador** [comment]
Oppps, that was exactly it, sorry.

**Pull request merged**
