### PR TITLE
Use url query params if response lacks OTP data

### LINKED ISSUE #417: Mode extraction in error message fails on bad OTP response
When planning a trip that times out on the OTP server (a separate issue altogether), the error response comes back without all of the nice metadata from OTP (e.g., requestParameters). This causes the code that pulls out the mode from that data to fail and results in a generic error message.

E.g.: Try [planning this trip](http://localhost:9966/#/?ui_activeSearch=3mxo1g15v&ui_activeItinerary=0&fromPlace=Herndon%20Stadium%2C%20Atlanta%2C%20GA%2C%20USA%3A%3A33.75631505992709%2C-84.40933227539064&toPlace=North%20Avenue%20Dining%20Hall%2C%20Atlanta%2C%20GA%2C%20USA%3A%3A33.770942684072246%2C-84.39165115356445&date=2021-07-15&time=14%3A32&arriveBy=false&mode=WALK%2CBUS%2CSUBWAY%2CTRAM&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=true&companies=&bannedRoutes=&numItineraries=3&otherThanPreferredRoutesPenalty=900&preferredRoutes=) with the latest `dev` branch running the ATL Rides config.

Note: this trip fails on the currently deployed UI for the ATL Rides instance.

You should see the generic `An error occurred while planning a trip` message.

### PR DESCRIPTION
**Pull request by landonreed**
Fixes #417. Note: this also yanks out some commented out code form `api.js` that no longer needs to be there.

image

You can try with the sample trip that's failing: http://localhost:9966/#/?ui_activeSearch=3mxo1g15v&ui_activeItinerary=0&fromPlace=Herndon%20Stadium%2C%20Atlanta%2C%20GA%2C%20USA%3A%3A33.75631505992709%2C-84.40933227539064&toPlace=North%20Avenue%20Dining%20Hall%2C%20Atlanta%2C%20GA%2C%20USA%3A%3A33.770942684072246%2C-84.39165115356445&date=2021-07-15&time=14%3A32&arriveBy=false&mode=WALK%2CBUS%2CSUBWAY%2CTRAM&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=true&companies=&bannedRoutes=&numItineraries=3&otherThanPreferredRoutesPenalty=900&preferredRoutes=

### CODE REVIEW

**Review by evansiroky — APPROVED** [review]

**Comment by evansiroky** [comment]
Approval conditional on updating testing snapshot.

**Review by miles-grant-ibigroup — APPROVED** [review]
Looks good to me! Clever using the empty string as false

**Comment by binh-dam-ibigroup** [comment]
Does this fix #413 too?

**Comment by binh-dam-ibigroup** [comment]
> Does this fix #413 too?

It doesn't, discard, that comment.

**Review by binh-dam-ibigroup — APPROVED** [review]
Ditto @evansiroky

**Pull request merged**
