### PR TITLE
nearby: use stoptime headsigns if applicable

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
It seems too easy... Did I miss some edge case?

### CODE REVIEW

**Review by amy-corson-ibigroup — APPROVED** [review]

**Comment by miles-grant-ibigroup** [comment]
@daniel-heppner-ibigroup do you have any idea why the snapshots are just ever so slightly off? What's going on here?

**Review by daniel-heppner-ibigroup — CHANGES_REQUESTED** [review]
I think what's happening is the duplicate checking code that follows the line you changed in stop.tsx is no longer matching a duplicate. Double check that and make sure it's okay, or change the duplicate checking code to maybe not use the headsign since it's now not consistent for a pattern?

**Comment by miles-grant-ibigroup** [comment]
> I think what's happening is the duplicate checking code that follows the line you changed in stop.tsx is no longer matching a duplicate. Double check that and make sure it's okay, or change the duplicate checking code to maybe not use the headsign since it's now not consistent for a pattern?

Good catch thanks!

**Review by daniel-heppner-ibigroup — APPROVED** [review]
snapshot update actually looks really good! At that stop the headsign doesn't show East Green Lake or Roosevelt Station.

**Pull request merged**
