### PR TITLE
Update otp-ui packages

### PR DESCRIPTION
**Pull request by amy-corson-ibigroup**
**Description:**

Update OTP-UI packages and fix imports 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Comment by amy-corson-ibigroup** [comment]
Note that because the latest version of `otp2-tile-overlay` requires passing `viewedRouteStops`, I've added a `null` value that will need to be taken out in #1270 (I can add that commit)

The latest version of `otp2-tile-overlay` also contains fixes for stop popup focus traps and it seemed more beneficial to update the package now and provide this stop gap, rather than wait.

**Comment by miles-grant-ibigroup** [comment]
> Note that because the latest version of `otp2-tile-overlay` requires passing `viewedRouteStops`, I've added a `null` value that will need to be taken out in #1270 (I can add that commit)
> 
> The latest version of `otp2-tile-overlay` also contains fixes for stop popup focus traps and it seemed more beneficial to update the package now and provide this stop gap, rather than wait.

OK I've blocked https://github.com/opentripplanner/otp-react-redux/pull/1270. When this is merged please make the commit/let me know

**Review by miles-grant-ibigroup — APPROVED** [review]

**Comment by miles-grant-ibigroup** [comment]
Unit tests are failing because the latest version of transitive is broken. If you downgrade that the tests will pass

**Comment by amy-corson-ibigroup** [comment]
@miles-grant-ibigroup jest was failing because newest version of transitive added a img file, I fixed it by adding a mock but can downgrade to 18 if we want! Let me know

**Review by josh-willis-arcadis — APPROVED** [review]
LGTM!

**Pull request merged**
