### PR TITLE
Change mobile container height on advanced panel open

### PR DESCRIPTION
**Pull request by amy-corson-ibigroup**
**Description:**

Adjust height on mobile advanced panel open so users can see all the choices at once

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Comment by amy-corson-ibigroup** [comment]
Hmm may actually be better to nix the new styled component and instead use conditional classnames? Curious what people think

**Comment by daniel-heppner-ibigroup** [comment]
I'm fine with the styled component. Why do you not like it?

**Review by daniel-heppner-ibigroup — APPROVED** [review]
I think this is fine as is, so I'll approve

**Review by josh-willis-arcadis — APPROVED** [review]
LGTM!

**Pull request merged**
