### PR TITLE
Pass "geocoderResultsOrder" config item to LocationFields

### PR DESCRIPTION
**Pull request by amy-corson-ibigroup**
**Description:**

Makes use of https://github.com/opentripplanner/otp-ui/pull/771 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Review by josh-willis-arcadis — APPROVED** [review]
looks great! TY for the changes

**Review by binh-dam-ibigroup — APPROVED** [review]
LGTM

**Comment by binh-dam-ibigroup** [comment]
Did someone break a11y tests?

**Comment by amy-corson-ibigroup** [comment]
> Did someone break a11y tests?

Oops just needed to handle if the geocoder config wasn't defined!

**Pull request merged**
