### PR TITLE
Add Column Context to stop schedule for AT

### PR DESCRIPTION
**Pull request by amy-corson-ibigroup**
Adds `scope="col"` to column headers in stop viewer so that they are navigable by screen readers and other ATs 

**PR Checklist:**
- [x] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [n/a] Are all languages supported (Internationalization/Localization)?
- [n/a] Are appropriate Typescript types implemented?

### CODE REVIEW

**Review by binh-dam-ibigroup — APPROVED** [review]
LGTM

**Review by AdrianaCeric — APPROVED** [review]
This is a great change and good catch. Would it be more efficient to do something like:
```
table th {
  scope: col;
}
```
in the relevant css file?

**Comment by binh-dam-ibigroup** [comment]
> This is a great change and good catch. Would it be more efficient to do something like:
> 
> ```
> table th {
>   scope: col;
> }
> ```
> 
> in the relevant css file?

@AdrianaCeric This is not a CSS attribute.

**Comment by AdrianaCeric** [comment]
> > This is a great change and good catch. Would it be more efficient to do something like:
> > ```
> > table th {
> >   scope: col;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the relevant css file?
> 
> @AdrianaCeric This is not a CSS attribute.

Wait I think you're right on that one haha 👍 really looked like it was

**Pull request merged**
