### PR TITLE
Transit Overlay: Restore missing OTP1 fields 

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
There was a lastUpdated field that was removed at some point. But now it's back!

### CODE REVIEW

**Review by daniel-heppner-ibigroup — COMMENTED** [review]
Are we maintaining support for OTP1 or are we translating an OTP2 vehicle into something that can be used with our code that still is looking for OTP1 props?

**Comment by miles-grant-ibigroup** [comment]
> Are we maintaining support for OTP1 or are we translating an OTP2 vehicle into something that can be used with our code that still is looking for OTP1 props?

OTP1 transit vehicle overlay uses OTP1 props to maintain OTP1 support and this PR makes sure that that overlay works correctly

**Review by daniel-heppner-ibigroup — APPROVED** [review]
sounds good to me

**Review by josh-willis-arcadis — APPROVED** [review]
LGTM!

**Pull request merged**
