### PR TITLE
A11y Announce Trip Search Status

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
## Description

This PR improves a11y by announcing trip search status pending/completion when using assistive technology.

**PR Checklist:**
- [x] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Comment by binh-dam-ibigroup** [comment]
Reassigning this back to change some headings per client request.

**Review by amy-corson-ibigroup — APPROVED** [review]
Works great! Thank you so much for adding the heading change as well!

**Review by miles-grant-ibigroup — APPROVED** [review]
All changes make sense and all is working well for me. I have one question about this behavior: 
Screenshot 2023-05-12 at 11 10 22 AM

It seems a bit strange to announce 3 places found but then not show them, but I'm not sure if that's related to this PR

**Comment by binh-dam-ibigroup** [comment]
Need to fix one undesired visual vertical offset before merging.

**Pull request merged**
