### PR TITLE
Remove calltaker index imports

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
**Description:**

This PR unbundles calltaker from non-calltaker instances.

For calltaker configs, import calltaker components as follows (as needed):
```js

import CallTakerControls from '../lib/components/admin/call-taker-controls'
import CallHistoryWindow from '../lib/components/admin/call-history-window'
import CallTakerPanel from '../lib/components/app/call-taker-panel'
import FieldTripWindows from '../lib/components/admin/field-trip-windows'
import MailablesWindow from '../lib/components/admin/mailables-window'
```

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Review by miles-grant-ibigroup — CHANGES_REQUESTED** [review]
I'm seeing an error when trying to run a call-taker config. Is there something I have to change in the config? 

Screenshot 2023-09-26 at 2 51 37 PM

**Comment by binh-dam-ibigroup** [comment]
> I'm seeing an error when trying to run a call-taker config. Is there something I have to change in the config?
> 
Yes, instead of importing from `../lib`, import the component from the module that defines it.

**Review by miles-grant-ibigroup — APPROVED** [review]
Working great, thanks so much for the changes

**Review by daniel-heppner-ibigroup — APPROVED** [review]
Nice change! Do you think we could add some documentation to explain how to enable the call taker module? Perhaps we need some better docs on config.js in general

**Pull request merged**
