### PR TITLE
Place editor a11y

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
This PR improves accessibility within the place editor with:
- keyboard focus cues
- visible field labels
- improved validation states and messages
- improved use of types.

### CODE REVIEW

**Review by amy-corson-ibigroup — APPROVED** [review]
Looks good! Wasn't able to find any issues.

**Comment by demory** [comment]
@binh-dam-ibigroup @amy-corson-ibigroup Maybe I'm missing something, but it seems like the "Edit this place" label for the button is preventing the place type and name from being announced in screenreader mode:

image

image

Should the button label also include this information?

**Comment by binh-dam-ibigroup** [comment]
> @binh-dam-ibigroup @amy-corson-ibigroup Maybe I'm missing something, but it seems like the "Edit this place" label for the button is preventing the place type and name from being announced in screenreader mode:
> 
> image
> 
> image
> 
> Should the button label also include this information?

@demory Yes, this was covered by #776, with the changes available on the dev branch.

**Review by demory — APPROVED** [review]

**Comment by demory** [comment]
@binh-dam-ibigroup approved but looks like a merge conflict now, can you please take a look?

**Pull request merged**
