### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [OTP-react-redux/OTP-RR Main UI](https://hosted.weblate.org/projects/otp-react-redux/otp-rr-main-ui/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by daniel-heppner-ibigroup — APPROVED** [review]
Needs fixes, to be done on Weblate

**Review by miles-grant-ibigroup — CHANGES_REQUESTED** [review]
The failing Percy tests makes sense since it's coming from the weblate repo. However, the code spell errors we should address -- perhaps one of our own PRs blocking the non-english yaml files?

**Comment by binh-dam-ibigroup** [comment]
> The failing Percy tests makes sense since it's coming from the weblate repo. However, the code spell errors we should address -- perhaps one of our own PRs blocking the non-english yaml files?

Yes @miles-grant-ibigroup, hold on to that thought.

**Review by miles-grant-ibigroup — APPROVED** [review]
Looks good to me -- Percy can be ignored since the PR origin repo is not ours.

**Pull request merged**
