### PR TITLE
Fix itinerary order

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
## Description

Responses for the different mode combinations requested to OTP were stored in the order they are returned.
The order of the responses could change when performing the same search again.

This PR ensures that the responses are stored in the same order as the mode combinations sent to OTP,
and also preserves (and fixes some) itinerary searches functionality with the Field Trip module.

## PR Checklist
- [na] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [na] Are all languages supported (Internationalization/Localization)?
- [na] Are appropriate Typescript types implemented?

### CODE REVIEW

**Comment by binh-dam-ibigroup** [comment]
Taking this back to draft and assigning to me, this PR broke the itinerary sorting!

**Review by miles-grant-ibigroup — CHANGES_REQUESTED** [review]
This works well for the metro UI, but breaks the field trip module

**Comment by binh-dam-ibigroup** [comment]
> This works well for the metro UI, but breaks the field trip module

@miles-grant-ibigroup Which issue are you seeing that doesn't occur on the dev branch? If it is "Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'pending')" while planning itineraries for a field trip, this error occurs on the dev branch too.

**Review by miles-grant-ibigroup — APPROVED** [review]
We will fix the field trip separately

**Review by miles-grant-ibigroup — CHANGES_REQUESTED** [review]
Actually the bug is dependent on this PR

**Comment by binh-dam-ibigroup** [comment]
> breaks the field trip module

How would changes from https://github.com/opentripplanner/otp-react-redux/pull/981/commits/31c000b6b2ff458f9985ef882f41520e45752c99 work?

**Comment by miles-grant-ibigroup** [comment]
No unfortunately field trip is still broken. I think the culprit is using `$set` instead of `$push` which means that the old itinerary results are overwritten

**Comment by binh-dam-ibigroup** [comment]
> No unfortunately field trip is still broken. I think the culprit is using `$set` instead of `$push` which means that the old itinerary results are overwritten

@miles-grant-ibigroup Could you provide steps to reproduce, please?

**Comment by miles-grant-ibigroup** [comment]
If you launch a field trip configuration with an OTP2 server, go to the new tab of the field trip requests window, select a trip with a date int he future and with a class size of over 40, and then click plan, you'll see that without this PR many results appear in the results pane. With this PR, only one result appears (and the number of passengers per vehicle is also hidden)

**Comment by binh-dam-ibigroup** [comment]
> If you launch a field trip configuration with an OTP2 server, go to the new tab of the field trip requests window, select a trip with a date int he future and with a class size of over 40, and then click plan, you'll see that without this PR many results appear in the results pane. With this PR, only one result appears (and the number of passengers per vehicle is also hidden)

@miles-grant-ibigroup Ok the correct redux update process was tricky to find, but I think this one is the good one.

**Review by daniel-heppner-ibigroup — APPROVED** [review]
Add this to the list of insane code written to make field trip continue working. Thank you for figuring this out, Binh.

**Pull request merged**
