### PR TITLE
new release: otp-ui refactor

### PR DESCRIPTION
**Pull request by evansiroky**
We're already starting to merge stuff from the auth0 refactors into dev, so I'm making this intermediate PR to master that contains only the stuff related to the otp-ui refactor so we can create a release with just that stuff to have some closure on otp-ui stuff.

This PR includes:

- #125
- #137
- #139
- #140
- #141
- #142
- #145
- #147
- #150
- #151
- #152
- #154
- #157
- #164

### CODE REVIEW

**Comment by evansiroky** [comment]
Has WIP label as it is waiting for a new release of otp-ui with https://github.com/opentripplanner/otp-ui/pull/140 included.

**Comment by evansiroky** [comment]
Ready for review

**Comment by binh-dam-ibigroup** [comment]
FYI @landonreed and @evansiroky : When testing, please update your map config as follows:
```yml
  baseLayers:
    - name: Streets
      url: //api.mapbox.com/styles/v1/mapbox/light-v10/tiles/{z}/{x}/{y}{retina}?access_token=...
      ...
      retina: "@2x"
```

**Comment by landonreed** [comment]
@evansiroky, can we set the base branch to beta and have semantic release roll out a beta release?

**Pull request closed without merging**
