### PR TITLE
otp-ui location field and geocoder refactor

### PR DESCRIPTION
**Pull request by evansiroky**
This PR replaces the location field and geocoding functionality using code sourced from otp-ui.

Also, this code fixes an annoying bug that would overlay the UserSettings component on the welcome screen when user data persistence was active.

### CODE REVIEW

**Comment by landonreed** [comment]
@evansiroky, I believe the user settings overlay was a feature ;)

**Comment by binh-dam-ibigroup** [comment]
IMO the UI tweak should be addressed as a separate issue.

**Comment by evansiroky** [comment]
See commit pushed to resolve styling issues. See https://github.com/opentripplanner/otp-ui/pull/89 for fixes to blurring of location-field.

**Pull request merged**
