### PR TITLE
Release request

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
(UPDATED)

This PR releases:
- trip realtime updates (#207),
- date/time format fixes in trip details (#218),
- removal of wizard mode when saving trips (#219), and
- fare display enhancements (#226).

### CODE REVIEW

**Review by landonreed — APPROVED** [review]
Looks fine, but could you please update the PR description to include the list of PRs this release encompasses? (Should be visible from the merge commits below.)

**Comment by binh-dam-ibigroup** [comment]
> Looks fine, but could you please update the PR description to include the list of PRs this release encompasses? (Should be visible from the merge commits below.)

Updated.

**Comment by binh-dam-ibigroup** [comment]
Blocking this realizing that the intent for the release was to also add fare enhancements to OTP-RR from https://github.com/opentripplanner/otp-ui/pull/209, but that was never implemented.

**Pull request merged**
