### PR TITLE
Use brand colors in date-time-picker

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
**Description:**

Small change to remove the basic whites and weird blues and instead use the brand colors! 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Review by amy-corson-ibigroup — APPROVED** [review]
Beautiful! Wondering how both you and second reviewer would feel about slightly higher font weight on the button text? It's a little hard to read the white text as is right now.

**Comment by miles-grant-ibigroup** [comment]
I wouldn't mind. Second reviewer what do you think

**Comment by binh-dam-ibigroup** [comment]
> I wouldn't mind. Second reviewer what do you think

I wouldn't mind, however this may exacerbate overflowing text in some cases, such as in this screenshot:
image

**Review by binh-dam-ibigroup — APPROVED** [review]
Looks good. I would vote in favor of bolding the drop down button text.

**Comment by miles-grant-ibigroup** [comment]
Let's table the bolding for now and do that in a separate PR

**Pull request merged**
