### PR TITLE
Route Row Background Color Indicates Active

### PR DESCRIPTION
**Pull request by amy-corson-ibigroup**
**Description:**

Route row now has a background color to indicate to users it is an active row. 

**PR Checklist:**
- [x] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [n/a] Are all languages supported (Internationalization/Localization)?
- [n/a] Are appropriate Typescript types implemented?

| Before | After |
|--------|-------|
|image|image|

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
Could maybe rename `patternActive` to just `active`

**Review by daniel-heppner-ibigroup — APPROVED** [review]
Agree with Miles on just called it `active`, but at the end of the day it doesn't really matter.

**Comment by daniel-heppner-ibigroup** [comment]
Also, I feel like we should be thinking about how to not have all these random colors hard coded all over the place.

**Comment by amy-corson-ibigroup** [comment]
Agree with the naming feedback but `active` is unfortunately an existing button prop, so renaming it this error: 
image

**Pull request merged**
