### PR TITLE
fix: Remove unneeded word wrap for itin times.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
## Description

This PR removes some unneeded word wrap for leg times (those starting from 10 to 12am/pm in the itinerary body) and trip durations in the itinerary summary.

Closes #982, a duplicate

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

### CODE REVIEW

**Comment by miles-grant-ibigroup** [comment]
Is this a duplicate of https://github.com/opentripplanner/otp-react-redux/pull/982?

**Comment by binh-dam-ibigroup** [comment]
> Is this a duplicate of #982?

A superset, but I did lose track of #982.

**Review by miles-grant-ibigroup — APPROVED** [review]
I've updated the pr description to close the duplicated PR. Things all work

**Review by amy-corson-ibigroup — APPROVED** [review]
Looks much better, thank you!

**Pull request merged**
