### PR TITLE
Make range unit work better with large ranges

### LINKED ISSUE #138: Jumbled elevation labels with large elevation changes
On certain itineraries with large elevation changes, the labels get all jumbled together. See example:

Screen Shot 2020-03-02 at 6 05 16 PM

### PR DESCRIPTION
**Pull request by evansiroky**
Fixes #138

### CODE REVIEW

**Review by binh-dam-ibigroup — APPROVED** [review]

**Review by landonreed — COMMENTED** [review]
Is there a sample trip you can share in the PR description that shows the fix? There is no trip URL in the referenced issue either.

**Comment by evansiroky** [comment]
This isn't deployed anywhere, but here is a screenshot I just took on my local machine that shows how the elevation units now display on a similar elevation profile with the changes made in this PR.

Screen Shot 2020-10-07 at 2 04 33 PM

**Review by landonreed — APPROVED** [review]
LGTM

**Pull request merged**
